
export const GET_WATCHES_LOAD = "GET_WATCHES_LOAD";
export const GET_WATCHES_SUCCESS = "GET_WATCHES_SUCCESS";
export const GET_WATCHES_FAIL = "GET_WATCHES_FAIL";

export const GET_WATCHES_BYBRAND_LOAD = "GET_WATCHES_BYBRAND_LOAD";
export const GET_WATCHES_BYBRAND_SUCCESS = "GET_WATCHES_BYBRAND_SUCCESS";
export const GET_WATCHES_BYBRAND_FAIL = "GET_WATCHES_BYBRAND_FAIL";

export const GET_ONE_WATCH_LOAD = "GET_ONE_WATCH_LOAD";
export const GET_ONE_WATCH_SUCCESS = "GET_ONE_WATCH_SUCCESS";
export const GET_ONE_WATCH_FAIL = "GET_ONE_WATCH_FAIL";

export const ADD_WATCH_LOAD = "ADD_WATCH_LOAD";
export const ADD_WATCH_SUCCESS = "ADD_WATCH_SUCCESS";
export const ADD_WATCH_FAIL = "ADD_WATCH_FAIL";

export const CLEAR_SUCCESS_WATCH = "CLEAR_SUCCESS_WATCH";
export const CLEAR_ERRORS_WATCH = "CLEAR_ERRORS_WATCH";
